# auto-generated by Cody. Be carefull
def gcd(a, b):
    """НОД"""
    return gcd(b, a % b) if b else a

def lcd(a, b):
    """НОК"""
    return a // gcd(a, b) * b

def compute_primes(n): 
    """Решето Эратосфена"""
    sieve = [True] * (n + 1) # решето
    primes = []     # список, в который будут добавляться простые числа
    
    for i in range(2, n + 1):   # изначально все числа не вычеркнуты
        if sieve[i]:
            primes.append(i)
            for j in range(i * i, n + 1, i):    # вычеркиваем все кратные числа начиная с i^2
                sieve[j] = False
    return primes
